---
- hosts: nexus_devices
  gather_facts: no
  connection: local

  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: terminal length 0
    nxos_command:
      provider: "{{ provider }}"
      commands:
        - "terminal length 0"

  - name: show vlan
    nxos_command:
      provider: "{{ provider }}"
      commands:
        - "show vlan brief"
      timeout: 40
    register: vlan


  #- debug: msg="{{ vlan.stdout }}"

  - local_action: copy content={{ vlan }} dest=/home/vinicius/Desktop/{{ inventory_hostname }}_nexus.txt
